name: Runtime Pipeline End To End Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Set up Mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: 5.7
        host port: 3306
        container port: 3306
        mysql database: pipeline_test
        mysql root password: pipeline_test
        mysql user: pipeline_test
        mysql password: pipeline_test
    - name: Start MySQL
      run: sudo service mysql restart
    - name: Set up Rabbitmq
      uses: nijel/rabbitmq-action@v1.0.0
      with:
        rabbitmq version: 3
    - name: Set up Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 0
    - name: check dockers
      run: docker ps
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=pipeline_test --silent; do
          sleep 1
        done
    - name: Test MySQL
      run:  mysql -upipeline_test -hlocalhost -ppipeline_test --default-character-set=utf8 -B -e "show databases;"
    - name: Install dependency
      run: |
        cd runtime/bamboo-pipeline/test
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        cd runtime/bamboo-pipeline/test
        cp -r ../../../bamboo_engine/ .
        cp -r ../pipeline .
        python manage.py migrate
        python manage.py celery worker
        pytest pipeline_test_use/tests
      env:
        PIPELINE_TEST_DB_TYPE: mysql
        PIPELINE_TEST_DB_NAME: pipeline_test
        PIPELINE_TEST_DB_USER: pipeline_test
        PIPELINE_TEST_DB_PWD: pipeline_test
